"""add match summary column

Revision ID: a0f1e44bf3bd
Revises: ebba3b058bbc
Create Date: 2026-06-06 17:00:28.889975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a0f1e44bf3bd'
down_revision: Union[str, None] = 'ebba3b058bbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('summary', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match', 'summary')
    # ### end Alembic commands ###
